# Generated by Django 4.1.7 on 2023-03-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en', models.CharField(max_length=50, verbose_name='Англійська')),
                ('uk', models.CharField(max_length=50, verbose_name='Українська')),
            ],
            options={
                'verbose_name': 'Переклад',
                'verbose_name_plural': 'Переклади',
                'ordering': ['id'],
            },
        ),
    ]
