# Generated by Django 4.1.7 on 2023-03-29 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perevod_app', '0004_alter_translation_en_alter_translation_uk'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValueState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel_state', models.DecimalField(decimal_places=2, max_digits=1000000)),
                ('bd_state', models.DecimalField(decimal_places=2, max_digits=1000000)),
            ],
        ),
    ]
